apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-g
  labels:
    app: nginx-g
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-g
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx-g
    spec:
      containers:
      - name: nginx-g
        image: 460876709067.dkr.ecr.sa-east-1.amazonaws.com/caps:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-g
spec:
  selector:
    app: nginx-g
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer