apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-b
  labels:
    app: nginx-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-b
  template:
    metadata:
      labels:
        app: nginx-b
    spec:
      containers:
      - name: nginx
        image: 460876709067.dkr.ecr.sa-east-1.amazonaws.com/caps:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-b
spec:
  selector:
    app: nginx-b
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer